# Generated by Django 4.0.4 on 2022-06-11 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_section_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='url',
            field=models.CharField(blank=True, default='index', max_length=50, null=True),
        ),
    ]
