# Generated by Django 4.0.4 on 2022-06-11 10:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=100)),
                ('date_created', models.CharField(default=datetime.datetime(2022, 6, 11, 15, 7, 42, 868458), max_length=100)),
                ('description', models.TextField()),
                ('image', models.CharField(default='https://th.bing.com/th/id/R.048fe00ae936f5b1ceef950ff314271d?rik=PPn3NcFhqZ46IA&riu=http%3a%2f%2fwww.vgmpf.com%2fWiki%2fimages%2fc%2fcb%2fNoPhoto.png&ehk=h28ESegf6decjqYgG7NuE1ZQ02oar%2bryghpicALBdeI%3d&risl=&pid=ImgRaw&r=0', max_length=100)),
                ('car_brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='car.carbrand')),
            ],
        ),
    ]
