# Generated by Django 4.0.4 on 2022-06-11 10:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='date_created',
            field=models.CharField(default=datetime.datetime(2022, 6, 11, 15, 8, 50, 861762), max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.CharField(default='https://th.bing.com/th/id/R.048fe00ae936f5b1ceef950ff314271d?rik=PPn3NcFhqZ46IA&riu=http%3a%2f%2fwww.vgmpf.com%2fWiki%2fimages%2fc%2fcb%2fNoPhoto.png&ehk=h28ESegf6decjqYgG7NuE1ZQ02oar%2bryghpicALBdeI%3d&risl=&pid=ImgRaw&r=0', max_length=100000),
        ),
    ]
