# Generated by Django 4.0.4 on 2022-06-11 11:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_alter_car_date_created_alter_car_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='url',
            field=models.CharField(blank=True, default='index', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='carbrand',
            name='url',
            field=models.CharField(blank=True, default='index', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='date_created',
            field=models.CharField(default=datetime.datetime(2022, 6, 11, 15, 59, 38, 798840), max_length=100),
        ),
    ]
