# Generated by Django 4.0.4 on 2022-06-11 11:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_car_url_carbrand_url_alter_car_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='carbrand',
            name='image',
            field=models.CharField(blank=True, default='https://th.bing.com/th/id/R.048fe00ae936f5b1ceef950ff314271d?rik=PPn3NcFhqZ46IA&riu=http%3a%2f%2fwww.vgmpf.com%2fWiki%2fimages%2fc%2fcb%2fNoPhoto.png&ehk=h28ESegf6decjqYgG7NuE1ZQ02oar%2bryghpicALBdeI%3d&risl=&pid=ImgRaw&r=0', max_length=100000, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='date_created',
            field=models.CharField(default=datetime.datetime(2022, 6, 11, 16, 4, 34, 803059), max_length=100),
        ),
    ]
