# Generated by Django 4.0.4 on 2022-06-11 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0004_carbrand_image_alter_car_date_created'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Car',
        ),
    ]
